package com.genner.formwork.model;

import com.genner.formwork.model.base.BaseVideoTv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoTv extends BaseVideoTv<VideoTv> {
	public static final VideoTv dao = new VideoTv().dao();
}
