package com.basic.framework.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseApiUrlConfig<M extends BaseApiUrlConfig<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 状态；0：启用，1：停用
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态；0：启用，1：停用
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 默认路线;0:不默认，1： 默认
	 */
	public M setDefaultPlay(java.lang.Integer defaultPlay) {
		set("default_play", defaultPlay);
		return (M)this;
	}
	
	/**
	 * 默认路线;0:不默认，1： 默认
	 */
	public java.lang.Integer getDefaultPlay() {
		return getInt("default_play");
	}

}
