package com.basic.framework.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("api_url_config", "id", ApiUrlConfig.class);
		arp.addMapping("user_info", "id", UserInfo.class);
		arp.addMapping("user_location", "id", UserLocation.class);
		arp.addMapping("video_tv", "id", VideoTv.class);
	}
}

