package com.basic.framework.model;

import com.basic.framework.model.base.BaseApiUrlConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiUrlConfig extends BaseApiUrlConfig<ApiUrlConfig> {
	public static final ApiUrlConfig dao = new ApiUrlConfig().dao();
}
