package com.basic.framework.model;

import com.basic.framework.model.base.BaseUserLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLocation extends BaseUserLocation<UserLocation> {
	public static final UserLocation dao = new UserLocation().dao();
}
