package com.genner.formwork.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideoTv<M extends BaseVideoTv<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 页面显示的名称
	 */
	public M setShowName(java.lang.String showName) {
		set("show_name", showName);
		return (M)this;
	}
	
	/**
	 * 页面显示的名称
	 */
	public java.lang.String getShowName() {
		return getStr("show_name");
	}

	/**
	 * 标题
	 */
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 描述
	 */
	public M setDescption(java.lang.String descption) {
		set("descption", descption);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescption() {
		return getStr("descption");
	}

	/**
	 * 播放地址
	 */
	public M setPlayUrl(java.lang.String playUrl) {
		set("play_url", playUrl);
		return (M)this;
	}
	
	/**
	 * 播放地址
	 */
	public java.lang.String getPlayUrl() {
		return getStr("play_url");
	}

	/**
	 * 图片地址
	 */
	public M setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}
	
	/**
	 * 图片地址
	 */
	public java.lang.String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 平台：QQ，iqiyi...
	 */
	public M setPlatform(java.lang.String platform) {
		set("platform", platform);
		return (M)this;
	}
	
	/**
	 * 平台：QQ，iqiyi...
	 */
	public java.lang.String getPlatform() {
		return getStr("platform");
	}

	/**
	 * 平分
	 */
	public M setScore(java.lang.String score) {
		set("score", score);
		return (M)this;
	}
	
	/**
	 * 平分
	 */
	public java.lang.String getScore() {
		return getStr("score");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
