package com.genner.formwork.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 账号
	 */
	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}

	/**
	 * 电话号码
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 电话号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 昵称
	 */
	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	/**
	 * 密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * vip权限等级(数字越大,等级权限越高)
	 */
	public M setVip(java.lang.Integer vip) {
		set("vip", vip);
		return (M)this;
	}
	
	/**
	 * vip权限等级(数字越大,等级权限越高)
	 */
	public java.lang.Integer getVip() {
		return getInt("vip");
	}

	/**
	 * 状态(0:正常,1:禁用,2:删除)
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态(0:正常,1:禁用,2:删除)
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 注册时间
	 */
	public M setRegisterTime(java.util.Date registerTime) {
		set("register_time", registerTime);
		return (M)this;
	}
	
	/**
	 * 注册时间
	 */
	public java.util.Date getRegisterTime() {
		return get("register_time");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
