package com.general.web.model;

import com.general.web.model.base.BaseProductInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductInfo extends BaseProductInfo<ProductInfo> {
	public static final ProductInfo dao = new ProductInfo().dao();
}
