package com.general.web.model;

import com.general.web.model.base.BaseSiteInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SiteInfo extends BaseSiteInfo<SiteInfo> {
	public static final SiteInfo dao = new SiteInfo().dao();
}
